services:
  # mssql docker
  rentacar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dz3n@ndZ3n@n!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - rentacarnet2024

  rentacar-api:
    restart: unless-stopped
    build:
      context: ./RentACar
    environment:
      - ConnectionStrings:DefaultConnection=Server=rentacar-sql,1433;Database=RentACarIB200149;User=sa;Password=Dz3n@ndZ3n@n!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7284:7284
    networks:
      - rentacarnet2024
    links:
      - rentacar-sql
      - rabbitmq
    depends_on:
      - rentacar-sql
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq_container'
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rentacarnet2024

  dodatni_api:
    restart: unless-stopped
    build:
      context: ./RentACarDodatni
    environment:
      - ConnectionStrings:DefaultConnection=Server=rentacar-sql,1433;Database=RentACarIB200149;User=sa;Password=Dz3n@ndZ3n@n!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7005:7005
    networks:
      - rentacarnet2024
    depends_on:
      - rentacar-sql
      - rabbitmq

networks:
  rentacarnet2024:
    driver: bridge
